[package]
name = "rsgit"
version = "0.1.0"
edition = "2024"
authors = ["Artem Stasyuk <stasyukartem2@gmail.com>"]
description = "A TUI Git client built with Rust"
repository = "https://github.com/xcroatoanx/rsgit"
license = "MIT"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
derive = "1.0.0"
ratatui = "0.30.2"
strum = "0.28.0"
